### PR TITLE
Add makefile to scaffolding

### PR DESCRIPTION
**Pull request by jmrodri**

### CODE REVIEW

**Comment by jmrodri** [comment]
```
$ make help

Usage:
  make <target>

General
  help             Display this help.

Build
  docker-build     Build docker image with the manager.
  docker-push      Push docker image with the manager.

Deployment
  install          Install CRDs into the K8s cluster specified in ~/.kube/config.
  uninstall        Uninstall CRDs from the K8s cluster specified in ~/.kube/config.
  deploy           Deploy controller to the K8s cluster specified in ~/.kube/config.
  undeploy         Undeploy controller from the K8s cluster specified in ~/.kube/config.
```

**Comment by jmrodri** [comment]
```
$ make deploy
kubectl apply -f target/kubernetes/kubernetes.yml
serviceaccount/java-op-operator created
service/java-op-operator created
rolebinding.rbac.authorization.k8s.io/java-op-operator-view created
deployment.apps/java-op-operator created
$ make install
customresourcedefinition.apiextensions.k8s.io/hellos.zeusville.com created
```

**Comment by jmrodri** [comment]
```
$ make docker-build IMG=quay.io/jesusr/java-operator:latest
mvn package -Dquarkus.container-image.build=true -Dquarkus.container-image.image=quay.io/jesusr/java-operator:latest
[INFO] Scanning for projects...
[INFO] 
[INFO] -----------------------< com.zeusville:java-op >------------------------
[INFO] Building java-op 0.0.1
[INFO] --------------------------------[ jar ]---------------------------------
[INFO] 
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ java-op ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 1 resource
[INFO] 
[INFO] --- maven-compiler-plugin:3.8.1:compile (default-compile) @ java-op ---
[INFO] Nothing to compile - all classes are up to date
[INFO] 
[INFO] --- maven-resources-plugin:2.6:testResources (default-testResources) @ java-op ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory /home/devel/jesusr/dev/java-op/src/test/resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.8.1:testCompile (default-testCompile) @ java-op ---
[INFO] No sources to compile
[INFO] 
[INFO] --- maven-surefire-plugin:2.12.4:test (default-test) @ java-op ---
[INFO] No tests to run.
[INFO] 
[INFO] --- maven-jar-plugin:2.4:jar (default-jar) @ java-op ---
[INFO] 
[INFO] --- quarkus-maven-plugin:1.12.2.Final:build (default) @ java-op ---
...
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  8.469 s
[INFO] Finished at: 2021-05-20T13:37:17-04:00
[INFO] ------------------------------------------------------------------------

```

**Comment by laxmikantbpandhare** [comment]
Just one comments/suggestions.

Can you please squash your commits? I usually get these comments on OLM PR's.

**Review by laxmikantbpandhare — APPROVED** [review]
Looks Good. Just added one comment about the commit Squash.

**Comment by jmrodri** [comment]
> Just one comments/suggestions.
> 
> Could you please squash your commits? I usually get these comments on OLM PR's.

Since we always squash the PR commits before merging it isn't as big of a deal with the PRs from SDK. For example, the olm_docs repo uses a merge commit when they merge PRs. When using merge commits it is more important to squash commits because it will merge them as is. This is precisely the reason I prefer squash and merge for `main` or `master` it keeps the history looking nice and it allows you to use as many commits as you want in the PR.

**Comment by laxmikantbpandhare** [comment]
Ah! got it. thank you for clarification.

**Pull request merged**
