### PR TITLE
chore: update to Quarkus 2.13.1.Final & JOSDK extension 4.0.2

### PR DESCRIPTION
**Pull request by metacosm**

### CODE REVIEW

**Review by jmrodri — APPROVED** [review]
/lgtm

**Review by laxmikantbpandhare — CHANGES_REQUESTED** [review]
Could you please update the test data as well just to be in sync with the changes made.

**Comment by laxmikantbpandhare** [comment]
> > Could you please update the test data as well just to be in sync with the changes made.
> 
> Hmm, actually what is that test data supposed to accomplish if it needs to be manually updated?

We can scaffold it as well in testdata. We just want it to sync with current changes.

**Comment by laxmikantbpandhare** [comment]
Created issue for the same - https://github.com/operator-framework/java-operator-plugins/issues/105

**Comment by metacosm** [comment]
Note that the more important issue is #75, until that's done, I don't think that we can claim to really validate what we output ;)

**Comment by laxmikantbpandhare** [comment]
> Note that the more important issue is #75, until that's done, I don't think that we can claim to really validate what we output ;)

@metacosm - agree with this.

**Pull request merged**
