### PR TITLE
Exposed endpoints for micrometer metrics

### PR DESCRIPTION
**Pull request by laxmikantbpandhare**
Added below changes in `pom.xml` file

```
    <dependency>
      <groupId>io.quarkus</groupId>
      <artifactId>quarkus-micrometer-registry-prometheus</artifactId>
      <version>${quarkus.version}</version>
    </dependency>
 ```
 
 It will expose the metrics endpoints

### CODE REVIEW

**Comment by metacosm** [comment]
I don't think that we should be making this change. It's up to users to decide how they want their metrics to be published.

**Comment by laxmikantbpandhare** [comment]
> I don't think that we should be making this change. It's up to users to decide how they want their metrics to be published.

@metacosm - So, you mean, we should not update the plugin and let user know that they can use this feature? Then, we can update tutorial accordingly.

**Comment by metacosm** [comment]
This can be shown as part of the tutorial and/or examples but I don't think it should be part of the code generated by the plug-in.

**Comment by laxmikantbpandhare** [comment]
> This can be shown as part of the tutorial and/or examples but I don't think it should be part of the code generated by the plug-in.

Got your point. Thank you.

**Comment by metacosm** [comment]
Closing this.

**Comment by laxmikantbpandhare** [comment]
> Closing this.

@metacosm - We were discussing the possible inclusion of the metrics part. I had word with @jmrodri, we enable metrics by default with our SDK. So it seems natural we do the same thing with Java projects.

We are planning to enable the Metrics by default.

**Comment by metacosm** [comment]
Metrics are enabled by default. You just need to provide a metrics provider. Which metrics provider is used should be up to the user. Do go operators automatically expose things over Prometheus?

**Comment by laxmikantbpandhare** [comment]
> Metrics are enabled by default. You just need to provide a metrics provider. Which metrics provider is used should be up to the user. Do go operators automatically expose things over Prometheus?

yes.

**Review by jmrodri — APPROVED** [review]
/lgtm

**Pull request merged**
