### PR TITLE
Bump to go 1.22, k8s 1.30 & kubebuilder 4.0

### PR DESCRIPTION
**Pull request by Neo2308**
* Bump go to 1.22
* Bump k8s to 1.30
* Bump ginkgo v1 -> v2
* Bump kubebuilder v3 -> v4
* Add copy of helper functions which were removed upstream

Relates to https://github.com/operator-framework/operator-sdk/issues/6730

### CODE REVIEW

**Review by csviri — APPROVED** [review]

**Review by metacosm — APPROVED** [review]

**Comment by Neo2308** [comment]
@grokspawn / @metacosm is this okay merge?

**Comment by Neo2308** [comment]
@grokspawn / @metacosm can you help merge this PR?

**Comment by laxmikantbpandhare** [comment]
Merged

**Pull request merged**
