### PR TITLE
Rename to v1alpha

### PR DESCRIPTION
**Pull request by jmrodri**
Signed-off-by: jesus m. rodriguez <jmrodri@gmail.com>

### CODE REVIEW

**Review by laxmikantbpandhare — APPROVED** [review]
v1alpha changes looks perfect.

**Comment by laxmikantbpandhare** [comment]
One question for this PR - **Memcached.java** file has field Version as v1. Do we need to change it to v1alpha1?

**Comment by jmrodri** [comment]
> @jmrodri - One question for this PR - **Memcached.java** file has field called Version as v1. Do we need to change it to v1alpha1?
I merged before I saw your question. No, the Version in **Memcached.java** is the version of that CRD. The `v1alpha` I am using in this PR is the version of the PLUGIN.

**Comment by laxmikantbpandhare** [comment]
> > @jmrodri - One question for this PR - **Memcached.java** file has field called Version as v1. Do we need to change it to v1alpha1?
> > I merged before I saw your question. No, the Version in **Memcached.java** is the version of that CRD. The `v1alpha` I am using in this PR is the version of the PLUGIN.

That's perfect then. Thank you for clarification.

**Pull request merged**
