### PR TITLE
bump k8s 1.25 and kb versions

### PR DESCRIPTION
**Pull request by laxmikantbpandhare**
bump k8s 1.25 and kb versions

### CODE REVIEW

**Comment by laxmikantbpandhare** [comment]
will look into errors once I am back.

**Comment by jmrodri** [comment]
@laxmikantbpandhare do we need to update the actual java portions for 1.25? https://github.com/operator-framework/java-operator-plugins/blob/main/pkg/quarkus/v1alpha/scaffolds/internal/templates/pomxml.go#L53-L62

**Comment by jmrodri** [comment]
You will also need to update the github action as part of this PR https://github.com/operator-framework/java-operator-plugins/blob/main/.github/workflows/test-unit.yml#L12

That needs to move to go 1.19

**Review by jmrodri — CHANGES_REQUESTED** [review]
Need to update github action as part of this PR. And I left a question regarding the scaffold pom.

**Comment by everettraven** [comment]
It also does not seem like Kubebuilder has been updated to have dependencies on K8s 1.25 as of that commit. I am planning to update this so this PR may need to be held until that is updated

**Comment by laxmikantbpandhare** [comment]
@everettraven @jmrodri - Updated all the dependencies according to suggestions. PTAL

**Review by everettraven — APPROVED** [review]
The changes look good to me. I would wait to merge until signoff from @jmrodri as well.

**Review by jmrodri — APPROVED** [review]
/lgtm

**Pull request merged**
