### PR TITLE
Bump java quarkus plugin scaffold to v1beta

### PR DESCRIPTION
**Pull request by jmrodri**
The scaffolded files have stabilized which warrants moving the plugin to v1beta

### CODE REVIEW

**Comment by laxmikantbpandhare** [comment]
@jmrodri - We can merge this PR now as we are done with `v0.5.0` release. I can test v1beta version changes through `init` and `create api` commands.

**Comment by jmrodri** [comment]
Oh wow this is old. Is it still relevant?

**Review by grokspawn — APPROVED** [review]

**Review by everettraven — APPROVED** [review]

**Pull request merged**
