### PR TITLE
fix: Generate src/main/java

### PR DESCRIPTION
**Pull request by jmrodri**

### CODE REVIEW

**Comment by jmrodri** [comment]
Fixes #32

**Comment by jmrodri** [comment]
Here's what it looks like immediately after init.

```
[jesusr@transam java-op]$ operator-sdk init --plugins quarkus  --domain zeusville.com --project-name java-op
[jesusr@transam java-op]$ tree
.
├── Makefile
├── pom.xml
├── PROJECT
└── src
    └── main
        ├── java
        └── resources
            └── application.properties

4 directories, 4 files
```

**Review by laxmikantbpandhare — COMMENTED** [review]
/lgtm

**Review by laxmikantbpandhare — APPROVED** [review]

**Comment by laxmikantbpandhare** [comment]
> Here's what it looks like immediately after init.
> 
> ```
> [jesusr@transam java-op]$ operator-sdk init --plugins quarkus  --domain zeusville.com --project-name java-op
> [jesusr@transam java-op]$ tree
> .
> ├── Makefile
> ├── pom.xml
> ├── PROJECT
> └── src
>     └── main
>         ├── java
>         └── resources
>             └── application.properties
> 
> 4 directories, 4 files
> ```

Yes, looks perfect **/src/main/java** path

**Comment by metacosm** [comment]
OK, that's kind of the solution I was hoping to avoid (i.e. create an empty file just to be able to create the directory) but that'll work. Maybe we should delete that `.placeholder` file when `create-api` is called so that things are cleaned up when not needed anymore?

**Comment by laxmikantbpandhare** [comment]
> OK, that's kind of the solution I was hoping to avoid (i.e. create an empty file just to be able to create the directory) but that'll work. Maybe we should delete that `.placeholder` file when `create-api` is called so that things are cleaned up when not needed anymore?

@metacosm - yes, we can delete `.placeholder` as it is not needed.

**Comment by jmrodri** [comment]
@metacosm @laxmikantbpandhare yes placeholder is there because you can't commit an empty directory to git and I assumed the user would like to commit their project to git. But I agree that we can remove it from create api since we add actual code there at that point.

**Comment by laxmikantbpandhare** [comment]
> @metacosm @laxmikantbpandhare yes placeholder is there because you can't commit an empty directory to git and I assumed the user would like to commit their project to git. But I agree that we can remove it from create api since we add actual code there at that point.

Cool, we will do the same.

**Pull request merged**
