### PR TITLE
bump java operator SDK version to latest 4.0.0

### PR DESCRIPTION
**Pull request by laxmikantbpandhare**
Update to JOSDK extension 4.0.0

### CODE REVIEW

**Review by everettraven — APPROVED** [review]
/lgtm

**Comment by laxmikantbpandhare** [comment]
@metacosm - It looks like `quarkus-sdk` needs a bump to v3.1.0 then only we can merge this PR until then I kept it on hold.

**Comment by laxmikantbpandhare** [comment]
@metacosm - Could you please take a look.

**Comment by laxmikantbpandhare** [comment]
Closing this as #99 is created by @metacosm

**Pull request closed without merging**
